theme : Forty
title : portfolio
Author: Satya Srinivas Paladugu
description: I'm Satya, an engineering student currently studying at AVV, Bengaluru.
My primary focus is on Artificial Intelligence and Machine Learning.
A passionate cinephile who loves discussing movies.
Feel free to connect with me on Discord sp.9696.
